# 커스텀 설정 (APP)
app:
  env: local

# 커스텀 설정 (JWT)
jwt:
  access-token-props:
    secret: 'ZlLHyRf4Ru3CnpVVl6hk9InHkAcHG07x82PufcFR4S4pKnLn0WJgtu4VQERoJauKi2hNIgWCuQF9aFQM7VJGlw=='
    expiration-time-milli-sec: 3600000
  refresh-token-props:
    secret: '3NuzNV3kkmNln/fqxyjqxKDA/1WaaS+V83KYTT8jmX1VpKsMskbqS+xFR3Cv1P9MmskDX3WdHcWka/dgvkGMQg=='
    expiration-time-milli-sec: 864000000

# 로그 설정
logging:
  level:
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# Tomcat 설정
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 10MB
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      force-request: true
      enabled: true

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/travelplan?serverTimezone=Asia/Seoul&charset=UTF-8'
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: me.travelplan.component.custommysqldialect.CustomMySqlDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false
  thymeleaf:
    mode: HTML
  flyway:
    baseline-version: 0
    out-of-order: true

storage:
  s3Bucket: s3.baruntravel.me
  s3Public: https://s3.ap-northeast-2.amazonaws.com/s3.baruntravel.me