version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "baruntravel"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19pd9dekplwk3"
s3_prefix = "baruntravel"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
